### ISSUE TITLE
bone flingers errors

### ISSUE THREAD

**Issue by cigumo** [ironhidegames/issues-kr4#105]
- [x] no armor raring display for Skeleton Warriors
<img width="831" alt="Screen Shot 2020-09-17 at 9 10 43 AM" src="https://user-images.githubusercontent.com/934821/93468690-bbba0e80-f8c5-11ea-9755-171880a5bc95.png">

- [x] rally point change is ignored if it happens while the soldier is running the spawn animation
<img width="204" alt="Screen Shot 2020-09-17 at 9 12 45 AM" src="https://user-images.githubusercontent.com/934821/93468856-02a80400-f8c6-11ea-97c3-1564629faa0e.png">

- [x] stage 15: skeletons walking into stable and blacksmith
![](https://i.imgur.com/USus6hG.png)

- [x] spawning in wrong places
![](https://cdn.discordapp.com/attachments/493772773081219073/765938344453865512/unknown.png)

**Comment by sunnydaler** [comment]
Skeleton knight has 0 armor

**Comment by Mmlh1** [comment]
https://www.youtube.com/watch?v=DOtuW84s5g0
Concerning spawning in wrong places.

**Comment by pablorealini** [comment]
This one:  "rally point change is ignored if it happens while the soldier is running the spawn animation" is already fixed.

**Comment by Mmlh1** [comment]
Indeed it is, and the armor rating is not a problem as they have no armor, so that's also fixed I assume.

**Comment by pablorealini** [comment]
Yes, I know that based on the look of the unit....they should have armor....but they do not.

**Comment by pablorealini** [comment]
**spawning in wrong places** I think it was also fixed. in a previous update, that path is secondary now. it was fixed here: https://github.com/ironhidegames/kingdomrush-x/commit/af8b3b1f341a2664a5e7c392933cd427a590f30d please confirm, closing for now.

**Comment by pablorealini** [comment]
I think this is fixed also: **_stage 15: skeletons walking into stable and blacksmith_**
