### ISSUE TITLE
leaks review

### ISSUE THREAD

**Issue by cigumo** [ironhidegames/issues-kr4#116]
- Veruk KRSquad: leaks when quitting the level with the spear soldiers still in the terrain
- KRSkill _targets: never released so the KRUnits inside it leak
- 

----------------------
### level / clean in and out
- Veruk: ok

### level / hero ulti only and out
- Veruk: KRSquad::init()  : leaks when quitting the level with the spear soldiers still in the terrain
- Mortemis: ok
- Tramin: ok
- Jigou ok

### level / only waves until failure
- Veru: ok

**Comment by pablorealini** [comment]
I fixed 2 leaks that I think are related to this issue here: https://github.com/ironhidegames/kingdomrush-x/commit/bc3acaa0b7c4846a8c045742d31c7342a772a544

Please confirm @cigumo
