### ISSUE TITLE
hero naga damage alternates when attacking

### ISSUE THREAD

**Issue by cigumo** [ironhidegames/issues-kr4#118]
![naga-damage mp4](https://user-images.githubusercontent.com/934821/93651332-87d70a00-f9e7-11ea-948e-08d629a389bb.gif)

**Comment by sunnydaler** [comment]
the damage boost aura is on.

**Comment by pablorealini** [comment]
fixed
The odd part is that the text reads 'improve the attack damage on the verge of death,' but this skill activates when there's 80% of life left... Weird.
