### ISSUE TITLE
infernal mage bullet offset

### ISSUE THREAD

**Issue by cigumo** [ironhidegames/issues-kr4#158]
Cuando dispara en algunos casos parece que el proyectil sale del centro en vez de las manos, eso pasa porque el trail del proyectil ya aparece cuando spawnea y no cuando se mueve, da una sensación de que el proyectil salio del centro. (ejemplo disparando hacia las 10am, se puede ver bien en la pantalla 1)

**Comment by pablorealini** [comment]
added a delay to cast the particle.
