### ISSUE TITLE
localization-Ja: Eiskalt's Japanese description is cut

### ISSUE THREAD

**Issue by sunnydaler** [ironhidegames/issues-kr4#211]
![20201009143602_1](https://user-images.githubusercontent.com/43391939/95547266-81174200-0a3d-11eb-8fbc-4b22ee1348f7.jpg)

HERO_EISKALT_DESCRIPTION = "ジョカルの子息として、エイスカルトは北方の支配者となるべく生を受けた。だがエイスカルトは執拗に人間を襲撃したことで、アルカズとエイスカルトの母の悩みの種となった。そして二人は泣く泣く力を合わせ、何百層にも連なる氷の奥底にエイスカルトを閉じ込めた。ヴェズナンの手で解放されるその時まで、エイスカルトは静かに眠ってい(cut from here)た。"

**Comment by pablorealini** [comment]
@sunnydaler  Do you understand Japanese? 
Is this ok as a smaller version?

`ジョカルの子息、エイスカルトは北方の支配者となる運命だった。しかし、人間を執拗に襲ったことがアルカズとエイスカルトの母の苦悩となった。二人は涙ながらに力を合わせ、何百層もの氷の奥深くにエイスカルトを閉じ込めた。ヴェズナンによって解放されるまで、エイスカルトは静かに眠り続けていた。」`
