### ISSUE TITLE
prevent enemies from attacking from outside the screen

### ISSUE THREAD

**Issue by cigumo** [ironhidegames/issues-kr4#231]

**Comment by Mmlh1** [comment]
Ranged enemies can attack your troops from off screen, but cannot be attacked back. 15 ish safe nodes to entrance for ranged attacks would probably fix this.

**Comment by Mmlh1** [comment]
This seems to be fixed in 1.15.4. Will see if it is truly fixed after more testing.

**Comment by Mmlh1** [comment]
This can presumably be closed.

**Comment by pablorealini** [comment]
Yes. closed.
