### ISSUE TITLE
localize vsync

### ISSUE THREAD

**Issue by cigumo** [ironhidegames/issues-kr4#233]
term vsync is not translated at all on any languages, even on those that use a different letters (russain, japanese, etc.)

**Comment by pablorealini** [comment]
Maybe we can translate this using chatgpt or something.

**Comment by cigumo** [comment]
Vsync is a technical term and in general it's not tranlsated. 

Asking chatgpt I got a similar answer: 
"Please note that “vsync” is a technical term and might be used as is in some languages" 

<img width="678" alt="Screenshot 2024-01-15 at 10 14 41" src="https://github.com/ironhidegames/issues-kr4/assets/934821/3f54378d-c9e3-440e-b333-a072e7b4affb">

I changed the chinese, and spanish entries.

**Comment by Emicon97** [comment]
Como hablante de español, nunca vi el término sincronización para referirse a vsync, en cambio creo que el término vsync está bastante extendido.

**Comment by pablorealini** [comment]
Se usa si. Entiendo igual que el hablante de español muchas veces usa
términos en inglés.
