### ISSUE TITLE
zombie summon discrepancies

### ISSUE THREAD

**Issue by sunnydaler** [ironhidegames/issues-kr4#235]
ground enemies | can summon cemetery zombie | can summon mortemis zombie
-------|----------------|---------------
chomp_bot* | x | x 
clockwork_spider* | x | o 
mechadwarf* | x | x 
sulfur_alchemist | o | x
nanoq_warbear* | x | o 
glacial_wolf* | x | x
apex_stalker* | x | o 
apex_shard* | x | x
frost_giant | o | x
svell_druid | o | x
frozen_heart | o | x
frozen_soul | o | o
ice_reaper | o | x
winter_lord | o | x
ice_golem | o | x
ninja_sheep | o | x
knight_rider (horse) | o | o
devoted_priest | o | x
arcane_magus | o | x
high_sorcerer | o | x
high_sorcerer_sheep* | x | x
high_sorcerer_sheep2* | x | x 
high_sorcerer_sheep_fast* | x | x 
hunting_dog* | x | o 
golem_house* | x | o 
war_wagon | o | o 
wicked_sisters_frog* | x | x
bullywags_channeler | o | x
bullywags_erudite | o | x
bullywags_golem* | x | x
ghost* | x | o 
haunted_skeleton | o | o
corrosive_soul* | x | o 
bone_carrier | o | x
lich | o | x

enemies with * have the following key
>			<key>custom_fills</key>
>			<dict>
>				<key>canSummonZombies</key>
>				<false/>
>			</dict>

1. imo, knight_rider, war_wagon and frozen_soul shouldn't summon zombies. what do devs think?
2. mortemis can't summon zombies from some enemies which don't have the above key. And vise versa.

**Comment by Mmlh1** [comment]
Additionally, cemetery spawns zombies from Amphiptere and Mortemis does not. Imo shouldn't spawn from Amphipteres.

**Comment by pablorealini** [comment]
Ok, got it....
I was checking MortemisSkill and I think I need to refactor the whole skills....there are a lot of problems with the implementation.

**Comment by pablorealini** [comment]
This is what I did:

1. I refactored and removed duplicated skills to avoid discrepancies.
2. Amphiptere, Knight rider (horse), War wagon,  Frozen should and also Camel rider (camel), elephants (both) will no summon zombies.

We need to test it because there are tons of enemies and probably some of them are not well configured.
