### ISSUE TITLE
leaping dragon stuck on path

### ISSUE THREAD

**Issue by cigumo** [ironhidegames/issues-kr4#243]
> A enemy is frozen on the path. Towers wont shoot it, I cant hurt it at all and its preventing me from finishing the level. Nice. Its one of the leaping dragon riders. Heres a screenshot.

![](https://i.gyazo.com/9afd50189f35f28452e6a5f6799e7b38.jpg)

https://steamcommunity.com/app/1367550/discussions/1/4835136555194501151/

**Comment by pablorealini** [comment]
Ok, found it....need to see how to fix it...
