### ISSUE TITLE
cooldown reduction notification text not shown

### ISSUE THREAD

**Issue by cigumo** [ironhidegames/issues-kr4#248]
https://steamcommunity.com/app/1367550/discussions/1/4835136555190616073/

> here is no cooldown reduction notification for the summon goons, hero respawn, and the soul impact after calling a wave early.

**Comment by pablorealini** [comment]
fixed here 9cc20c0038b4614f7c67676a1d66b92da208a14e
Need some gfx tweak

**Comment by pablorealini** [comment]
fixed here https://github.com/ironhidegames/kingdomrush-x/commit/9cc20c0038b4614f7c67676a1d66b92da208a14e
Need some gfx tweak
