### ISSUE TITLE
elven rangers turned back from frogs can't be attacked 

### ISSUE THREAD

**Issue by cigumo** [ironhidegames/issues-kr4#254]
> The Elven Rangers who turn back from frogs(affected by Wicked Sisters)CANNOT BE ATTACKED, so they just stand there and keep attacking. The game will not end because of this ghost-kind enemy's being. 

http://support.ironhidegames.com/a/tickets/67706

**Comment by cigumo** [comment]
Danche could not reproduce it.

**Comment by sunnydaler** [comment]
https://cdn.discordapp.com/attachments/493772773081219073/768147434785734696/ezgif.com-gif-maker_4.mp4

**Comment by cigumo** [comment]
![ezgif com-gif-maker_4 mp4-200h mov](https://user-images.githubusercontent.com/934821/96618839-d542e180-12db-11eb-95bd-dbd6287c0f17.gif)

**Comment by Mmlh1** [comment]
https://www.youtube.com/watch?v=D1Hax4sdH_8

**Comment by cigumo** [comment]
It will fix itself once the unit walks. It seems to be related to the state of the recently created unit not updated if instantiated in a blocked state.

**Comment by pablorealini** [comment]
Can we confirm that this is still an issue? because we fixed some bugs around Polymorfed units..

Edit: don't worry, this bug is still there.
