### ISSUE TITLE
elf archers can't be killed in stage 14 / Lestat.UA@steam

### ISSUE THREAD

**Issue by cigumo** [ironhidegames/issues-kr4#259]
14. City of Lozagon
2 times in a row
14 / 15 wave
2 elf archers on road in left-bottom section of enemy mage ring
cant be killed, nothing helped, have to quit, progress blocked
Hero - Tramin
Towers - Archers, Orks, Witches, Evil Tree, Dark Elfs

![1367550_screenshots_20201020001531_1](https://user-images.githubusercontent.com/934821/96787816-c8e88280-13c8-11eb-99d8-13124a3be5f4.jpg)

Also: 
https://steamcommunity.com/app/1367550/discussions/1/4835136555202852875/
https://youtu.be/kUs4RdKrRfk

**Comment by Mmlh1** [comment]
Probably #254, as Witches were used.

**Comment by pablorealini** [comment]
Probably yes. closed since I already fixed that bug.
