### ISSUE TITLE
corpses spawning in invalid paths

### ISSUE THREAD

**Issue by cigumo** [ironhidegames/issues-kr4#262]
https://steamcommunity.com/app/1367550/discussions/1/4835136555205457922/

![XERvwcS](https://user-images.githubusercontent.com/934821/96790443-30083600-13cd-11eb-85fd-6420aa4da2ab.png)

**Comment by cigumo** [comment]
related to #105?

**Comment by pablorealini** [comment]
fixed with other commit.
