### ISSUE TITLE
objects not picking up target's path

### ISSUE THREAD

**Issue by sunnydaler** [ironhidegames/issues-kr4#75]
these head to the pre-destined paths only

- [x] hero_tramin_ultimate_bomb
 ![tramin](https://user-images.githubusercontent.com/43391939/92936003-86a45b00-f484-11ea-9166-ffaac82f66fb.gif)

- [x] hero_eiskalt - frosty
 ![frosty](https://user-images.githubusercontent.com/43391939/92935926-6d9baa00-f484-11ea-9c54-0c8d91892e54.gif)

- [x] hero_jacko_horse
![horse](https://user-images.githubusercontent.com/43391939/92935956-74c2b800-f484-11ea-82db-c1014bedd967.gif)

- [x] hero_naga - tidal_wave
![ezgif com-video-to-gif (2)](https://user-images.githubusercontent.com/43391939/93694136-3a6faf80-fb43-11ea-952c-e35a016b7160.gif)

**Comment by Mmlh1** [comment]
As far as I can tell, it defaults to the path with lowest index that crosses the selected point.

**Comment by Mmlh1** [comment]
Also applies to ultimate_hero_mammoth
